In [1]:
import pandas as pd

In [2]:
tadf_pl_ds = pd.read_excel("tadf_train_corrected_for_annotation.xlsx", sheet_name="4_ml_cols_only")
tadf_pl_ds.head()

,_id,doi,solvent,standard_value,smiles,corrected
0,0,https://doi.org/10.1016/j.cej.2022.135775,toluene,638.0,N1=CC=C(C=C1)C=1C=C2N=C3C(=NC2=CC1C1=CC=NC=C1)...,1
1,1,https://doi.org/10.1016/j.cej.2022.135775,toluene,639.0,N1=CC=C(C=C1)C=1C=C2N=C3C4=C(C5=C(C3=NC2=CC1C1...,1
2,2,https://doi.org/10.1016/j.dyepig.2023.111250,toluene,465.0,C1(=CC=CC=C1)C1=NC(=NC(=N1)C1=CC=CC=C1)C1=C(C=...,1
3,17,https://doi.org/10.1016/j.cej.2020.127591,toluene,415.0,C1=CC=CC=2C=3C=CC4=C(C3N(C12)C1=NC=C(N=C1)N1C=...,1
4,18,https://doi.org/10.1016/j.cej.2020.127591,toluene,444.0,C1=C2C=3C4=C(C=CC3N(C2=CC=C1)C1=NC=C(N=C1)N1C2...,1

In [2]:
from rdkit import Chem

In [4]:
# add canonical smiles
tadf_pl_ds["canonical_smiles"] = tadf_pl_ds["smiles"].apply(Chem.CanonSmiles)

In [3]:
solvent2smiles={
    'toluene': 'CC1=CC=CC=C1',
    'thf': 'O1CCCC1',
    '2-methf': 'CC1OCCC1',
    'hexane': 'CCCCCC',
    'dichloromethane': 'ClCCl',
    'ch2cl2': 'ClCCl',
    'chcl3': 'ClC(Cl)Cl',
    'tetrahydrofuran': 'O1CCCC1',
    'chloroform': 'C(Cl)(Cl)Cl',
    'cyclohexane': 'C1CCCCC1',
    'dcm': 'ClCCl',
    'ch3cn': 'C(C)#N',
    'methylcyclohexane': 'CC1CCCCC1',
    '2-me-thf': 'CC1OCCC1',
    'dmso': 'CS(=O)C',
    'meoh': 'CO',
    'dmf': 'CN(C=O)C',
    'phme': 'CC1=CC=CC=C1',
    'mecn': 'C(C)#N',
    'acetonitrile': 'C(C)#N',
}

In [4]:
for k, v in solvent2smiles.items():
    solvent2smiles[k] = Chem.CanonSmiles(v)

In [5]:
def get_solvent_smiles(solvent):
    if not solvent or type(solvent) != str:
        return None
    return solvent2smiles[solvent.lower()]
# tadf_pl_ds["solvent_smiles"] = tadf_pl_ds["solvent"].apply(get_solvent_smiles)

In [8]:
tadf_pl_by_canonsmiles = tadf_pl_ds.groupby(["canonical_smiles", "solvent_smiles"])

In [23]:
group_sizes = tadf_pl_by_canonsmiles.size().sort_values(ascending=False)
group_sizes_large = group_sizes[group_sizes > 1]

In [26]:
Chem.CanonSmiles("O=C(c1c2cc(c3ccc(N(c4ccc(OCCCCCCN5c6ccccc6c7ccccc75)cc4)c8ccc(OCCCCCCN9c%10ccccc%10c%11ccccc%119)cc8)cc3)cc1)c%12cc(c%13ccc(N(c%14ccc(OCCCCCCN%15c%16ccccc%16c%17ccccc%17%15)cc%14)c%18ccc(OCCCCCCN%19c%20ccccc%20c%21ccccc%21%19)cc%18)cc%13)ccc%12C2=O")

'O=C1c2ccc(-c3ccc(N(c4ccc(OCCCCCCn5c6ccccc6c6ccccc65)cc4)c4ccc(OCCCCCCn5c6ccccc6c6ccccc65)cc4)cc3)cc2C(=O)c2ccc(-c3ccc(N(c4ccc(OCCCCCCn5c6ccccc6c6ccccc65)cc4)c4ccc(OCCCCCCn5c6ccccc6c6ccccc65)cc4)cc3)cc21'

In [24]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    for group_key in group_sizes_large.index:
        print(f"Size: {group_sizes[group_key]}")
        display(tadf_pl_by_canonsmiles.get_group(group_key).drop(columns=["smiles", "solvent_smiles"]))

Size: 4

,_id,doi,solvent,standard_value,corrected,canonical_smiles
442,377,https://doi.org/10.1039/D1TC05696D,Toluene,476.0,0,N#Cc1cc(-c2cccc3c2[nH]c2ccccc23)c(-c2cccc3c2[n...
443,378,https://doi.org/10.1039/D1TC05696D,Toluene,496.0,0,N#Cc1cc(-c2cccc3c2[nH]c2ccccc23)c(-c2cccc3c2[n...
444,380,https://doi.org/10.1039/D1TC05696D,Toluene,484.0,0,N#Cc1cc(-c2cccc3c2[nH]c2ccccc23)c(-c2cccc3c2[n...
445,381,https://doi.org/10.1039/D1TC05696D,Toluene,477.0,0,N#Cc1cc(-c2cccc3c2[nH]c2ccccc23)c(-c2cccc3c2[n...

Size: 4

,_id,doi,solvent,standard_value,corrected,canonical_smiles
330,177,https://doi.org/10.1016/j.dyepig.2021.109580,toluene,578.0,0,CC1(C)c2ccccc2N(c2ccc3nc4c5ccccc5c5ccccc5c4nc3...
420,334,https://doi.org/10.1039/D0TC01995J,toluene,567.0,0,CC1(C)c2ccccc2N(c2ccc3nc4c5ccccc5c5ccccc5c4nc3...
525,493,https://doi.org/10.1039/D3TC02352D,PhMe,595.0,0,CC1(C)c2ccccc2N(c2ccc3nc4c5ccccc5c5ccccc5c4nc3...
526,494,https://doi.org/10.1039/D3TC02352D,PhMe,568.0,0,CC1(C)c2ccccc2N(c2ccc3nc4c5ccccc5c5ccccc5c4nc3...

Size: 4

,_id,doi,solvent,standard_value,corrected,canonical_smiles
59,33,https://doi.org/10.1016/j.orgel.2017.06.034,toluene,667.0,1,COc1ccc(N(c2ccc(OC)cc2)c2ccc(-c3ccc4c(c3)C(=O)...
243,34,https://doi.org/10.1016/j.orgel.2017.06.034,toluene,715.0,0,COc1ccc(N(c2ccc(OC)cc2)c2ccc(-c3ccc4c(c3)C(=O)...
244,35,https://doi.org/10.1016/j.orgel.2017.06.034,toluene,667.0,0,COc1ccc(N(c2ccc(OC)cc2)c2ccc(-c3ccc4c(c3)C(=O)...
245,36,https://doi.org/10.1016/j.orgel.2017.06.034,toluene,708.0,0,COc1ccc(N(c2ccc(OC)cc2)c2ccc(-c3ccc4c(c3)C(=O)...

Size: 3

,_id,doi,solvent,standard_value,corrected,canonical_smiles
469,413,https://doi.org/10.1039/D1TC04918F,toluene,505.0,0,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1ccc2...
470,414,https://doi.org/10.1039/D1TC04918F,toluene,589.0,0,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1ccc2...
471,415,https://doi.org/10.1039/D1TC04918F,toluene,674.0,0,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1ccc2...

Size: 3

,_id,doi,solvent,standard_value,corrected,canonical_smiles
429,348,https://doi.org/10.1039/C9TC02467K,toluene,474.0,0,O=C(c1ccc2sc3ccccc3c2c1)c1cc(-c2ccc(N(c3ccccc3...
430,349,https://doi.org/10.1039/C9TC02467K,toluene,498.0,0,O=C(c1ccc2sc3ccccc3c2c1)c1cc(-c2ccc(N(c3ccccc3...
431,350,https://doi.org/10.1039/C9TC02467K,toluene,480.0,0,O=C(c1ccc2sc3ccccc3c2c1)c1cc(-c2ccc(N(c3ccccc3...

Size: 3

,_id,doi,solvent,standard_value,corrected,canonical_smiles
409,323,https://doi.org/10.1039/D1TC02778F,CH2Cl2,500.0,0,c1ccc(-c2nnc(-c3c(-n4c5ccccc5c5ccccc54)c(-n4c5...
410,324,https://doi.org/10.1039/D1TC02778F,CH2Cl2,496.0,0,c1ccc(-c2nnc(-c3c(-n4c5ccccc5c5ccccc54)c(-n4c5...
411,325,https://doi.org/10.1039/D1TC02778F,CH2Cl2,532.0,0,c1ccc(-c2nnc(-c3c(-n4c5ccccc5c5ccccc54)c(-n4c5...

Size: 3

,_id,doi,solvent,standard_value,corrected,canonical_smiles
276,81,https://doi.org/10.1016/j.dyepig.2024.112118,Toluene,371.0,0,c1ccc2c(c1)sc1ccc(-n3c4ccccc4c4cc(C56CC7CC(CC(...
277,82,https://doi.org/10.1016/j.dyepig.2024.112118,Toluene,375.0,0,c1ccc2c(c1)sc1ccc(-n3c4ccccc4c4cc(C56CC7CC(CC(...
281,86,https://doi.org/10.1016/j.dyepig.2024.112118,Toluene,447.0,0,c1ccc2c(c1)sc1ccc(-n3c4ccccc4c4cc(C56CC7CC(CC(...

Size: 3

,_id,doi,solvent,standard_value,corrected,canonical_smiles
274,79,https://doi.org/10.1016/j.dyepig.2024.112118,Toluene,371.0,0,c1ccc2c(c1)sc1ccc(-n3c4ccccc4c4ccccc43)cc12
275,80,https://doi.org/10.1016/j.dyepig.2024.112118,Toluene,376.0,0,c1ccc2c(c1)sc1ccc(-n3c4ccccc4c4ccccc43)cc12
280,85,https://doi.org/10.1016/j.dyepig.2024.112118,Toluene,445.0,0,c1ccc2c(c1)sc1ccc(-n3c4ccccc4c4ccccc43)cc12

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
472,416,https://doi.org/10.1039/C8TC04721A,THF,550.0,0,CCCCCCn1c2ccccc2c2c1c1c3ccccc3n(-c3ccc(C(=O)c4...
473,417,https://doi.org/10.1039/C8TC04721A,THF,524.0,0,CCCCCCn1c2ccccc2c2c1c1c3ccccc3n(-c3ccc(C(=O)c4...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
301,113,https://doi.org/10.1016/j.orgel.2022.106645,Toluene,670.0,0,N#CC(C#N)=C1c2ccccc2-c2cc(-c3ccc(N(c4ccccc4)c4...
302,114,https://doi.org/10.1016/j.orgel.2022.106645,Toluene,802.0,0,N#CC(C#N)=C1c2ccccc2-c2cc(-c3ccc(N(c4ccccc4)c4...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
642,640,https://doi.org/10.1039/D1TC04933J,toluene,497.0,0,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1c(C#...
643,641,https://doi.org/10.1039/D1TC04933J,toluene,483.0,0,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1c(C#...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
303,115,https://doi.org/10.1016/j.orgel.2022.106645,Toluene,670.0,0,N#CC(C#N)=C1c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)c...
304,116,https://doi.org/10.1016/j.orgel.2022.106645,Toluene,802.0,0,N#CC(C#N)=C1c2ccc(-c3ccc(N(c4ccccc4)c4ccccc4)c...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
299,111,https://doi.org/10.1016/j.dyepig.2017.11.027,THF,459.0,0,Clc1c(-n2c3ccccc3c3ccccc32)nc(-n2c3ccccc3c3ccc...
300,112,https://doi.org/10.1016/j.dyepig.2017.11.027,THF,462.0,0,Clc1c(-n2c3ccccc3c3ccccc32)nc(-n2c3ccccc3c3ccc...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
278,83,https://doi.org/10.1016/j.dyepig.2024.112118,Toluene,404.0,0,CC(C)(C)c1ccc(-c2cc3c4c(c2)Oc2ccccc2B4c2ccccc2...
279,84,https://doi.org/10.1016/j.dyepig.2024.112118,Toluene,413.0,0,CC(C)(C)c1ccc(-c2cc3c4c(c2)Oc2ccccc2B4c2ccccc2...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
132,818,https://doi.org/10.1002/adom.202100970,toluene,522.0,1,CC1(C)c2ccccc2N(c2ccc(C(=O)c3ccccc3)cc2)c2ccccc21
383,269,https://doi.org/10.1016/j.cej.2020.127418,toluene,498.0,0,CC1(C)c2ccccc2N(c2ccc(C(=O)c3ccccc3)cc2)c2ccccc21

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
592,576,https://doi.org/10.1039/C7TC00457E,toluene,465.0,0,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1cc(C...
593,577,https://doi.org/10.1039/C7TC00457E,toluene,458.0,0,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1cc(C...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
590,574,https://doi.org/10.1039/C7TC00457E,toluene,494.0,0,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1cc(C...
591,575,https://doi.org/10.1039/C7TC00457E,toluene,488.0,0,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1cc(C...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
588,572,https://doi.org/10.1039/C7TC00457E,toluene,480.0,0,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1cc(C...
589,573,https://doi.org/10.1039/C7TC00457E,toluene,476.0,0,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1cc(C...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
214,901,https://doi.org/10.1016/j.dyepig.2021.109781,toluene,650.0,1,CC1(C)c2ccccc2N(c2ccc(-c3cc(-n4c5ccccc5c5ccccc...
215,902,https://doi.org/10.1016/j.dyepig.2021.109781,toluene,634.0,1,CC1(C)c2ccccc2N(c2ccc(-c3cc(-n4c5ccccc5c5ccccc...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
384,272,https://doi.org/10.1016/j.dyepig.2021.109395,CH2Cl2,536.0,0,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1nc(-...
385,273,https://doi.org/10.1016/j.dyepig.2021.109395,CH2Cl2,561.0,0,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1nc(-...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
554,537,https://doi.org/10.1039/D2TC01406H,toluene,432.0,0,CC1(C)OB(c2ccc(-c3c4ccccc4c(-c4ccc(-c5ccc6c(c5...
555,538,https://doi.org/10.1039/D2TC01406H,toluene,432.0,0,CC1(C)OB(c2ccc(-c3c4ccccc4c(-c4ccc(-c5ccc6c(c5...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
529,497,https://doi.org/10.1039/D3TC02352D,PhMe,630.0,0,CC1(C)c2ccccc2N(c2ccc3nc4c5cccnc5c5ncccc5c4nc3...
530,498,https://doi.org/10.1039/D3TC02352D,PhMe,586.0,0,CC1(C)c2ccccc2N(c2ccc3nc4c5cccnc5c5ncccc5c4nc3...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
252,50,https://doi.org/10.1016/j.dyepig.2024.112233,toluene,440.0,0,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1ccc(...
613,601,https://doi.org/10.1039/D0NJ00905A,toluene,439.0,0,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1ccc(...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
329,176,https://doi.org/10.1016/j.dyepig.2021.109580,toluene,632.0,0,CC1(C)c2ccccc2N(c2cccc3nc4c5ccccc5c5ccccc5c4nc...
421,335,https://doi.org/10.1039/D0TC01995J,toluene,620.0,0,CC1(C)c2ccccc2N(c2cccc3nc4c5ccccc5c5ccccc5c4nc...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
611,599,https://doi.org/10.1039/C9CP05907E,toluene,535.0,0,Cc1cc(N2c3ccccc3Sc3ccccc32)ccc1-c1cc(-c2ccc(N3...
612,600,https://doi.org/10.1039/C9CP05907E,toluene,525.0,0,Cc1cc(N2c3ccccc3Sc3ccccc32)ccc1-c1cc(-c2ccc(N3...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
297,109,https://doi.org/10.1016/j.dyepig.2017.11.027,THF,462.0,0,Clc1nc(-n2c3ccccc3c3ccccc32)c(Cl)c(-n2c3ccccc3...
298,110,https://doi.org/10.1016/j.dyepig.2017.11.027,THF,446.0,0,Clc1nc(-n2c3ccccc3c3ccccc32)c(Cl)c(-n2c3ccccc3...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
594,578,https://doi.org/10.1039/C9TC06497D,toluene,546.0,0,Cc1cc(C)c(B(c2ccc(-c3nc(Cl)nc(-c4ccccc4)n3)cc2...
595,579,https://doi.org/10.1039/C9TC06497D,toluene,533.0,0,Cc1cc(C)c(B(c2ccc(-c3nc(Cl)nc(-c4ccccc4)n3)cc2...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
620,613,https://doi.org/10.1039/C5TC00779H,THF,605.0,0,CC(C)(C)c1ccc(N2C(=O)c3cccc4c(/C=C/c5ccc6cc(N(...
621,614,https://doi.org/10.1039/C5TC00779H,THF,608.0,0,CC(C)(C)c1ccc(N2C(=O)c3cccc4c(/C=C/c5ccc6cc(N(...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
527,495,https://doi.org/10.1039/D3TC02352D,PhMe,645.0,0,CC1(C)c2ccccc2N(c2cnc3nc4c5ccccc5c5ccccc5c4nc3...
528,496,https://doi.org/10.1039/D3TC02352D,PhMe,601.0,0,CC1(C)c2ccccc2N(c2cnc3nc4c5ccccc5c5ccccc5c4nc3...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
531,499,https://doi.org/10.1039/D3TC02352D,PhMe,672.0,0,CC1(C)c2ccccc2N(c2cnc3nc4c5cccnc5c5ncccc5c4nc3...
532,500,https://doi.org/10.1039/D3TC02352D,PhMe,606.0,0,CC1(C)c2ccccc2N(c2cnc3nc4c5cccnc5c5ncccc5c4nc3...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
569,553,https://doi.org/10.1039/C7TC04934J,THF,535.0,0,CC1(C)c2ccccc2N(c2ccc(C(=O)c3cc(-n4c5ccccc5c5c...
570,554,https://doi.org/10.1039/C7TC04934J,THF,518.0,0,CC1(C)c2ccccc2N(c2ccc(C(=O)c3cc(-n4c5ccccc5c5c...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
142,828,https://doi.org/10.1039/C6RA03281H,ch2cl2,553.0,1,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1ccc2...
143,829,https://doi.org/10.1039/C6RA03281H,CH2Cl2,520.0,1,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1ccc2...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
476,426,https://doi.org/10.1039/C5TC00350D,CHCl3,455.0,0,N#Cc1c(-n2c(-c3ccccc3)nc3ccccc32)cc(-n2c(-c3cc...
477,427,https://doi.org/10.1039/C5TC00350D,CHCl3,432.0,0,N#Cc1c(-n2c(-c3ccccc3)nc3ccccc32)cc(-n2c(-c3cc...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
147,833,https://doi.org/10.1039/C9TC02195G,THF,498.0,1,N#Cc1cc(-c2nc(-c3ccccc3)nc(-c3ccccc3)n2)ccc1-n...
466,407,https://doi.org/10.1039/C9TC05855A,THF,489.0,0,N#Cc1cc(-c2nc(-c3ccccc3)nc(-c3ccccc3)n2)ccc1-n...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
295,107,https://doi.org/10.1016/j.orgel.2018.03.027,CH2Cl2,491.0,0,N#Cc1ccc(-c2c(-n3c4ccccc4c4ccccc43)c(-n3c4cccc...
296,108,https://doi.org/10.1016/j.orgel.2018.03.027,CH2Cl2,497.0,0,N#Cc1ccc(-c2c(-n3c4ccccc4c4ccccc43)c(-n3c4cccc...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
581,565,https://doi.org/10.1039/D0TC01811B,Toluene,440.0,0,N#Cc1ccc(-c2c3ccccc3c(-c3ccc(-c4nc5c6ccccc6c6c...
582,566,https://doi.org/10.1039/D0TC01811B,Toluene,460.0,0,N#Cc1ccc(-c2c3ccccc3c(-c3ccc(-c4nc5c6ccccc6c6c...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
579,563,https://doi.org/10.1039/D0TC01811B,Toluene,420.0,0,N#Cc1ccc(-c2c3ccccc3c(-c3cccc(-c4nc5c6ccccc6c6...
580,564,https://doi.org/10.1039/D0TC01811B,Toluene,451.0,0,N#Cc1ccc(-c2c3ccccc3c(-c3cccc(-c4nc5c6ccccc6c6...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
216,903,https://doi.org/10.1016/j.dyepig.2017.04.024,toluene,518.0,1,N#Cc1ccc(-c2cc(C#N)cc(-c3ccc(C#N)cc3)c2N2c3ccc...
350,218,https://doi.org/10.1016/j.dyepig.2017.04.024,toluene,561.0,0,N#Cc1ccc(-c2cc(C#N)cc(-c3ccc(C#N)cc3)c2N2c3ccc...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
345,202,https://doi.org/10.1016/j.dyepig.2023.111200,toluene,508.0,0,N#Cc1ccc(-n2c3ccccc3c3ccccc32)c(-c2nc(-c3cc(C#...
370,249,https://doi.org/10.1016/j.jlumin.2023.119787,toluene,513.0,0,N#Cc1ccc(-n2c3ccccc3c3ccccc32)c(-c2nc(-c3cc(C#...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
550,527,https://doi.org/10.1039/D4NJ03124E,CH2Cl2,462.0,0,N#Cc1ccc2c(c1)c1ccccc1n2-c1ccccc1-c1nc(-c2cccc...
551,528,https://doi.org/10.1039/D4NJ03124E,CH2Cl2,450.0,0,N#Cc1ccc2c(c1)c1ccccc1n2-c1ccccc1-c1nc(-c2cccc...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
552,529,https://doi.org/10.1039/D4NJ03124E,CH2Cl2,490.0,0,N#Cc1cccc2c1c1ccccc1n2-c1ccccc1-c1nc(-c2ccccc2...
553,530,https://doi.org/10.1039/D4NJ03124E,CH2Cl2,474.0,0,N#Cc1cccc2c1c1ccccc1n2-c1ccccc1-c1nc(-c2ccccc2...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
577,561,https://doi.org/10.1039/C9TC04418C,toluene,619.0,0,N#Cc1nc2c3ccc(-n4c5ccc(-c6ccc(N(c7ccccc7)c7ccc...
578,562,https://doi.org/10.1039/C9TC04418C,toluene,663.0,0,N#Cc1nc2c3ccc(-n4c5ccc(-c6ccc(N(c7ccccc7)c7ccc...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
575,559,https://doi.org/10.1039/C9TC04418C,toluene,559.0,0,N#Cc1nc2c3ccc(-n4c5ccc(-c6ccccc6)cc5c5cc(-c6cc...
576,560,https://doi.org/10.1039/C9TC04418C,toluene,593.0,0,N#Cc1nc2c3ccc(-n4c5ccc(-c6ccccc6)cc5c5cc(-c6cc...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
474,418,https://doi.org/10.1039/C8TC04721A,THF,543.0,0,O=C(c1ccc(-n2c3ccccc3c3c4c(c5ccccc5n4-c4ccccc4...
475,419,https://doi.org/10.1039/C8TC04721A,THF,520.0,0,O=C(c1ccc(-n2c3ccccc3c3c4c(c5ccccc5n4-c4ccccc4...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
102,730,https://doi.org/10.1002/ange.201802060,THF,576.0,1,O=C(c1ccc(N2c3ccccc3Oc3ccccc32)cc1)c1ccc2c(c1)...
362,239,https://doi.org/10.1016/j.cej.2022.138919,THF,573.0,0,O=C(c1ccc(N2c3ccccc3Oc3ccccc32)cc1)c1ccc2c(c1)...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
603,591,https://doi.org/10.1039/D0TC02016H,THF,569.0,0,O=C(c1ccc(N2c3ccccc3Oc3ccccc32)cc1)c1ccc2c(c1)...
604,592,https://doi.org/10.1039/D0TC02016H,THF,533.0,0,O=C(c1ccc(N2c3ccccc3Oc3ccccc32)cc1)c1ccc2c(c1)...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
601,589,https://doi.org/10.1039/D0TC02016H,THF,568.0,0,O=C(c1ccc(N2c3ccccc3Oc3ccccc32)cc1)c1ccc2c(c1)...
602,590,https://doi.org/10.1039/D0TC02016H,THF,530.0,0,O=C(c1ccc(N2c3ccccc3Oc3ccccc32)cc1)c1ccc2c(c1)...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
113,772,https://doi.org/10.1002/anie.201802060,THF,575.0,1,O=C(c1ccc(N2c3ccccc3Oc3ccccc32)cc1)c1ccc2c(c1)...
361,236,https://doi.org/10.1016/j.cej.2022.138919,THF,575.0,0,O=C(c1ccc(N2c3ccccc3Oc3ccccc32)cc1)c1ccc2c(c1)...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
586,570,https://doi.org/10.1039/C7TC00457E,toluene,495.0,0,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1cc(C...
587,571,https://doi.org/10.1039/C7TC00457E,toluene,478.0,0,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1cc(C...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
412,326,https://doi.org/10.1039/C9TC02927C,toluene,501.0,0,O=C(c1ccccc1)c1ccc(-n2c3ccccc3c3c4c(c5ccccc5n4...
413,327,https://doi.org/10.1039/C9TC02927C,toluene,510.0,0,O=C(c1ccccc1)c1ccc(-n2c3ccccc3c3c4c(c5ccccc5n4...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
493,452,https://doi.org/10.1039/D2TC00731B,CH2Cl2,400.0,0,O=P(c1ccc(-n2c3ccccc3c3ccccc32)cc1)(c1ccc(-n2c...
494,453,https://doi.org/10.1039/D2TC00731B,CH2Cl2,408.0,0,O=P(c1ccc(-n2c3ccccc3c3ccccc32)cc1)(c1ccc(-n2c...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
514,478,https://doi.org/10.1039/D3TC03395C,toluene,445.0,0,O=S(=O)(c1ccc(-n2c3ccc(OCCn4c5ccc(-n6c7ccccc7c...
515,479,https://doi.org/10.1039/D3TC03395C,toluene,447.0,0,O=S(=O)(c1ccc(-n2c3ccc(OCCn4c5ccc(-n6c7ccccc7c...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
512,476,https://doi.org/10.1039/D3TC03395C,toluene,448.0,0,O=S(=O)(c1ccc(-n2c3ccc(OCCn4c5ccccc5c5ccccc54)...
513,477,https://doi.org/10.1039/D3TC03395C,toluene,457.0,0,O=S(=O)(c1ccc(-n2c3ccc(OCCn4c5ccccc5c5ccccc54)...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
597,582,https://doi.org/10.1039/C9TC03582F,toluene,442.0,0,O=S(=O)(c1ccccc1)c1ccc(N2c3ccccc3C3(c4ccccc42)...
598,583,https://doi.org/10.1039/C9TC03582F,toluene,459.0,0,O=S(=O)(c1ccccc1)c1ccc(N2c3ccccc3C3(c4ccccc42)...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
495,454,https://doi.org/10.1039/D0TC01144D,Toluene,366.0,0,O=c1c2ccccc2oc2cc(-c3cc(-n4c5ccccc5c5ccccc54)c...
496,455,https://doi.org/10.1039/D0TC01144D,Toluene,375.0,0,O=c1c2ccccc2oc2cc(-c3cc(-n4c5ccccc5c5ccccc54)c...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
497,456,https://doi.org/10.1039/D0TC01144D,Toluene,365.0,0,O=c1c2ccccc2oc2ccc(-c3cc(-n4c5ccccc5c5ccccc54)...
498,457,https://doi.org/10.1039/D0TC01144D,Toluene,374.0,0,O=c1c2ccccc2oc2ccc(-c3cc(-n4c5ccccc5c5ccccc54)...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
284,95,https://doi.org/10.1016/j.dyepig.2022.110634,toluene,555.0,0,c1ccc(-c2ccc3c(c2)c2cc(-c4ccccc4)ccc2n3-c2cc3n...
285,96,https://doi.org/10.1016/j.dyepig.2022.110634,toluene,566.0,0,c1ccc(-c2ccc3c(c2)c2cc(-c4ccccc4)ccc2n3-c2cc3n...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
2,2,https://doi.org/10.1016/j.dyepig.2023.111250,toluene,465.0,1,c1ccc(-c2nc(-c3ccccc3)nc(-c3ccccc3-n3c4ccccc4c...
450,387,https://doi.org/10.1039/C9TC03808F,toluene,473.0,0,c1ccc(-c2nc(-c3ccccc3)nc(-c3ccccc3-n3c4ccccc4c...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
636,634,https://doi.org/10.1039/D4NR03955F,toluene,478.0,0,CC(C)(C)c1ccc(N2c3ccc(C(C)(C)C)cc3B3c4cc(C(C)(...
637,635,https://doi.org/10.1039/D4NR03955F,toluene,470.0,0,CC(C)(C)c1ccc(N2c3ccc(C(C)(C)C)cc3B3c4cc(C(C)(...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
272,77,https://doi.org/10.1016/j.dyepig.2017.03.032,THF,425.0,0,c1ccc(-n2c(-c3cccc4ccccc34)nc3c4ccccc4c4ccccc4...
273,78,https://doi.org/10.1016/j.dyepig.2017.03.032,THF,446.0,0,c1ccc(-n2c(-c3cccc4ccccc34)nc3c4ccccc4c4ccccc4...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
30,262,https://doi.org/10.1016/j.dyepig.2024.111981,toluene,579.0,1,c1ccc(N(c2ccccc2)c2ccc(-c3ccc4nc5c6cccnc6c6ncc...
31,263,https://doi.org/10.1016/j.dyepig.2024.111981,toluene,575.0,1,c1ccc(N(c2ccccc2)c2ccc(-c3ccc4nc5c6cccnc6c6ncc...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
508,470,https://doi.org/10.1039/D2TC04403J,toluene,594.0,0,c1ccc2c(c1)Oc1ccccc1N2c1cc2nc3c(nc2cc1N1c2cccc...
509,471,https://doi.org/10.1039/D2TC04403J,toluene,625.0,0,c1ccc2c(c1)Oc1ccccc1N2c1cc2nc3c(nc2cc1N1c2cccc...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
634,630,https://doi.org/10.1039/D0TC01897J,toluene,505.0,0,c1ccc2c(c1)[nH]c1cc3[nH]c4ccccc4c3cc12
635,631,https://doi.org/10.1039/D0TC01897J,toluene,502.0,0,c1ccc2c(c1)[nH]c1cc3[nH]c4ccccc4c3cc12

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
335,192,https://doi.org/10.1016/j.dyepig.2021.109781,THF,558.0,0,c1ccc2c(c1)c1ccccc1n2-c1cc(-c2ccc(-c3cc(-n4c5c...
336,193,https://doi.org/10.1016/j.dyepig.2021.109781,THF,555.0,0,c1ccc2c(c1)c1ccccc1n2-c1cc(-c2ccc(-c3cc(-n4c5c...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
626,619,https://doi.org/10.1039/C6TC03063G,CH2Cl2,535.0,0,c1ccc2c(c1)c1ccccc1n2-c1ccc2c(c1)c1cc(-n3c4ccc...
627,620,https://doi.org/10.1039/C6TC03063G,CH2Cl2,487.0,0,c1ccc2c(c1)c1ccccc1n2-c1ccc2c(c1)c1cc(-n3c4ccc...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
624,617,https://doi.org/10.1039/C6TC03063G,CH2Cl2,535.0,0,c1ccc2c(c1)c1ccccc1n2CCCCCCOc1ccc2c(c1)c1ccccc...
625,618,https://doi.org/10.1039/C6TC03063G,CH2Cl2,490.0,0,c1ccc2c(c1)c1ccccc1n2CCCCCCOc1ccc2c(c1)c1ccccc...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
323,164,https://doi.org/10.1016/j.orgel.2018.11.018,CH2Cl2,512.0,0,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1ccc2...
324,165,https://doi.org/10.1016/j.orgel.2018.11.018,CH2Cl2,502.0,0,CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1n2-c1ccc2...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
351,219,https://doi.org/10.1016/j.orgel.2019.03.044,DMF,423.0,0,FC(F)(F)c1ccc(-n2c(-c3ccc(-c4ccc(-n5c6ccccc6c6...
352,220,https://doi.org/10.1016/j.orgel.2019.03.044,DMF,440.0,0,FC(F)(F)c1ccc(-n2c(-c3ccc(-c4ccc(-n5c6ccccc6c6...

Size: 2

,_id,doi,solvent,standard_value,corrected,canonical_smiles
282,93,https://doi.org/10.1016/j.dyepig.2022.110634,toluene,516.0,0,c1cnc2c(c1)c1nc3cc(-n4c5ccccc5c5ccccc54)c(-n4c...
283,94,https://doi.org/10.1016/j.dyepig.2022.110634,toluene,555.0,0,c1cnc2c(c1)c1nc3cc(-n4c5ccccc5c5ccccc54)c(-n4c...

In [13]:
df = pd.read_excel("tadf_train_corrected_for_annotation.xlsx", sheet_name="6_resolved_duplicates")

In [14]:
def canonical_smiles(smiles):
    try:
        canon_smiles = Chem.CanonSmiles(smiles)
    except Exception as e:
        print(f"Error processing SMILES: {smiles}, Error: {e}")
        return None
    return canon_smiles

In [15]:
df["_temp_canonical_smiles"] = df["canonical_smiles"].apply(canonical_smiles)

In [16]:
df = df.drop(columns=["canonical_smiles"])
df = df.rename(columns={"_temp_canonical_smiles": "canonical_smiles"})

In [17]:
df["solvent_smiles"] = df["solvent"].apply(get_solvent_smiles)

In [18]:
with pd.ExcelWriter("tadf_train_corrected_for_annotation.xlsx", engine="openpyxl", mode="a") as writer:
    df.to_excel(writer, sheet_name="7_resolved_duplicates", index=False)